spring:
  application:
    name: config-server
  profiles:
    active: subversion
  cloud:
    config:
      server:
        svn:
          uri: http://www.baidu.com
          search-paths: FrameWork_v3/WebContent/spring-cloud-config-file/config-client
          username: weijisheng
          password: 75454
          default-label: trunk
  
    
server:
  port: 7001
  
  
